### ISSUE TITLE
TITLE - Add page title tags

### ISSUE THREAD

**Issue by nicolasarths** [nicolasarths/nicolasarths#5]
I forgot to add the page titles... Has to be done... right?

**Comment by sauravraj188** [comment]
I am interested in this work
Please assign it to me

**Comment by nicolasarths** [comment]
You are the first one to collaborate with me. You are very welcome! The page titles are always contained inside the higher heading tags, so if you don't speak portuguese you'll still be able to find out what the title is. Good luck!

**Comment by nicolasarths** [comment]
Are you still up to this task?

**Comment by nicolasarths** [comment]
@savi001
